apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
    spec:
      containers:
      - name: sentiment-api
        image: gcr.io/project-5d0c5cd6-794c-4b56-bf8/sentiment-api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
