apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/project-5d0c5cd6-794c-4b56-bf8/sentiment-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://sentiment-api:8000"
